### ISSUE TITLE
Transfer character check functionality to PSD

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1089]
**Feature**
The existing character check functionality is to be merged/ported across to PSD. All forms should solely be available here.

**Task list**
- [x] Move existing character check forms to PSD

**Comment by warrensearle** [comment]
Some tasks following User Testing session on 6 December:

- [ ] In the character section, the answer options to the question What is your Sex should match what the answer options on the live Platform (i.e. Male, Female, Prefer not to say).
- [ ] After the questionnaire has been submitted it is still possible to edit the Character Checks answers (go to review screen and notice the change links)
- [ ] When completing the form there is a blank Professional details page
