### ISSUE TITLE
Implement two-factor authentication (2FA) on Apply

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1220]
## Background
2FA is now commonplace for all online accounts. JAC Digital would like to implement 2FA to add an extra layer of protection for sensitive personal candidate data held on Apply. In addition, we would like to implement a session timeout, so that candidates are automatically logged out after a pre-determined time period.

This epic branch is called: feature/epic-1220-implement-2FA

## User Story
As a candidate, I would like 2FA to be implemented on Apply so that my sensitive personal data is more secure.

## Benefit(s) to user (if not already clear from User story)
If a candidate's device is mislaid or stolen, they will be logged out of Apply and their data will remain confidential.

## Feature(s) Description
- [x] Add `UK Mobile Phone number` field to Candidate profile on Apply
- [x] Add instructions: Please input your UK Mobile phone number in the format 0xxxxxxxxxx. This number will be verified and used for Two-factor authentication.
- [x] First validate number to ensure format correct for UK mobile phone, i.e. 0+10 digits
- [x] If correct, a 6-digit code is sent by SMS to that mobile number and a modal pops up asking candidates to input the code
- [x] If the code is correct, the number is updated as verified, if incorrect, the candidate can repeat the process
- [x] Once the number is verified, 2FA is activated
- [x] 2FA is required every 7 days
- [x] Implement a session timeout of 2 hours' inactivity (QUESTION: how do we measure inactivity?)
- [x] The phone number field in the Personal details section of the application form is no longer included; this is replaced by the UK Mobile phone number field, which is read only
<img width="669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGJNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13e23b687fadb69c3fe75de96c2bcb13fce5c6bd/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when:

- [ ] A new, mandatory mobile phone field is added to the Candidate profile section on Apply
- [ ] Each time the mobile phone field is updated, a mechanism is triggered to verify the number by SMS
- [ ] 2FA is activated the first time this field is populated
- [ ] 2FA must be performed at least every 7 days
- [ ] Candidates' login sessions time out after 2 hours
- [ ] The mobile phone field appears as a read only field under Personal details on the application form

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1220?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by drieJAC** [comment]
'2FA is required every 7 days'
 'Implement a session timeout of 2 hours'

If a user gets logged out after 2 hrs then wont they need to login again with 2FA?

**Comment by nickaddy** [comment]
No, they just log back in normally, without 2FA. 
2FA is only required once a week, i.e. if I'm asked this morning when I log in at 9am, I will next be asked - at the earliest - at 9am next Monday.

**Comment by drieJAC** [comment]
@nickaddy What happens if a user loses their phone and they havent logged in for over a week?
They will be unable to login to reset their number.
At the point of sign in would it be worth us giving them the choice of either SMS or email to enter the verification code?

**Comment by nickaddy** [comment]
@drieJAC I'd like to keep this as simple as possible, so suggest in such cases candidates will have to contact the exercise team, be verified and provide an alternate mobile number, e.g. partner, workphone etc for 2FA.

**Comment by drieJAC** [comment]
See: https://www.notifications.service.gov.uk/
For how to use: notifications-node-client
Which we currently use in our nodescript: testNotification.js

**Comment by drieJAC** [comment]
We should compare sending via the GovUK Notification service vs using firebase to send the sms

**Comment by drieJAC** [comment]
The db fields added for this ticket are:

candidate/documents/personalDetails/mobilePhone (string)
and:
candidate/documents/personalDetails/mobilePhoneVerifiedAt (timestamp)

Note that legacy applications store the user's phone number so we need to ensure this still gets displayed, eg when viewing applications in apply and in admin.
